### ISSUE TITLE
Visual Logger can not set topic name and partition

### ISSUE THREAD

**Issue by billkuku** [onewayautomation/ogamma-logger#11]
Hello,
i have set the variables to log in `address space` at `Visual Logger for OPC`, looks good.
but i can't set topic name and partition for it, it will be cleared after setting and saving...
if i use default topic name (name showed in `Address Space`), i can't consume the Data with my Kafka-Consumer from that topic.

can any one help me? thank you in advance.

**Comment by RavilN** [comment]
Hi,
In the current version, if in the configuration file it is set to log to database other than Kafka, fields Topic Name, Key name and partition are not used and not saved. So first please check if database type is set to Kafka. In the default config file there should be few entries under node timeSeriesDataBases, the very first one of them is used. 
In the coming new version database settings are going to be configurable from GUI. Should be available soon, perhaps in couple of days.

Regards, Ravil

**Comment by RavilN** [comment]
In version 0.8.2 column names match with the options in time-series database: for Kafka it is Topic Name and Key Name, for Influx DB - measurement and tags. In PostgreSQL these settings are not used.
For InfluxDB there are few modes to generate measurements and tags automatically, settings can be configured via GUI.
