### ISSUE TITLE
Ogamma logger logs all values as unknown into influxdb

### ISSUE THREAD

**Issue by mjkl-gh** [onewayautomation/ogamma-logger#12]
After messing around a bit I had to recreate a instance since it started spamming segmentation faults.

I accidentally pulled latest instead of the version I was on before (probably 7.1) now when logging to influxdb every thing gets written to table unknown where n is unknown instead of d where n=id

**Comment by RavilN** [comment]
Hi,
There a lots of changes in version 0.8.1, including mapping to InfluxDB measurements and tags now is configurable. Upgrade from older versions might not pick up right settings for that mapping, sorry. Upgrades will be really supported after version 1.0.
To keep the same mapping as in versions before 0.8.1, you need to open InfluxDB connection settings via menu Settings/Time-Series Database, and set option "Key Name Generation Mode" to "Use Variable Id", and in the field "Database Specific settings/json" enter {"measurement":"d"} (including curly brackets).
Sorry for inconvenience, Ravil

**Comment by mjkl-gh** [comment]
Aah that explains, It does seem like an enormous improvement. I've tried the settings you've suggested. It now fills the variables into the correct measurement (d), however Key name is still unknown while setting key name generation mode to use variable id

**Comment by RavilN** [comment]
Cannot be reproduced in the latest version.
