### ISSUE TITLE
Ogamma (0.8.5) auto-reconnect problem

### ISSUE THREAD

**Issue by ghost** [onewayautomation/ogamma-logger#13]
Hi everyone,
I have installed ogamma 0.8.5 and I'm collecting data from two remote PLC to influxdb_v2, but when a network problem occurs, I have to restart the ogamma container to reactivate the data acquisition.

Thanks

Domenico

**Comment by RavilN** [comment]
Hi Domenico,
Could you please specify, in what part network problems occur: between ogamma and PLC, or between ogamma and InfluxDB, or both? It should handle disconnections on both sides. 
If problem persists, please zip your ./data folder and send to support at onewayautomation.com for investigation.
Also, you mention "container", so assuming that you are using Docker installation, right?
Thank you, Ravil

**Comment by ghost** [comment]
Hi Ravil,
The problem is between ogamma and PLC, infact have problem to see data also on ogamma web interface on port 4880.
I will collect logs and i will send to your support in the next days.
I'm using docker installation on debian virtual machine.
Thanks
Domenico
