### ISSUE TITLE
Failed to synchronize instance settings

### ISSUE THREAD

**Issue by JulLeuverink** [onewayautomation/ogamma-logger#16]
Hi,

I get following Error when I first docker-compose up my Stack.

`Failed to synchronize instance settings with configuration database, error: Detected invalid state (the instance [258057383933900F] has no configuration) at /home/user/workspace/uarest/ogamma-logger-lib/src/GlobalVariables.cpp/752`

However on the second start everything seems to work except the timesereisDB (postgres/timescaleDB) I preconfigured doesn't exist.

**Comment by JulLeuverink** [comment]
So, this error occures when you delete the config.json.instance.json and start the ogamma-logger container without reseting the configuration database. 

For me these steps fixed it:
1. Stop the whole stack 
2. Delete everything the ogamma container createt (logs, instance folder, config.json.instance.json, etc.)
3. Remove ogamma container 
4. Remove volumes of ogamma container and configdb 
5. Start the stack again

You will loose all configurations done after you first startet ogamma-logger. I wouldn't recommend this for production environments.

**Comment by RavilN** [comment]
I thought this happens in the fresh installation. 
If you delete file config.json.instance.json, yes, you would have this kind of issue. 
Thank you for looking at this!
