### ISSUE TITLE
http://localhost:4880: This site can't be reached.

### ISSUE THREAD

**Issue by tengann** [onewayautomation/ogamma-logger#17]
I am trying to install ogamma Visual Logger on my Windows 7 Professional PC. I saw that Docker Desktop require Windows 10 therefore I installed Docker on my PC by downloading Docker Toolbox instead. 

I managed to clone the repository by running: 
`git clone https://github.com/onewayautomation/ogamma-logger.git` 
and thereafter start desired set of containers using docker-compose command:
`docker-compose -f docker-compose.yml -f portainer.yml -f timescaledb.yml -f grafana.yml up -d`

Here is the output from my Windows PowerShell.
![image](https://user-images.githubusercontent.com/48940092/100334239-79702480-300e-11eb-8f48-82e247d92e3b.png)

However, when I try to open http://localhost:4880, I get the error: `This site can't be reached.`
![image](https://user-images.githubusercontent.com/48940092/100334532-e1bf0600-300e-11eb-9696-69401596c172.png)

What am I doing wrong here?

**Comment by RavilN** [comment]
Hi,
Need the log files to figure out what is going on here. You can find them under subfolder data/[InstanceId]/logs. If you send the content of the whole folder data as a zip file to support@onewayautomation.com, we will investigate.
As a workaround, you can try the Windows distr package for now and run it on a real machine.
Thank you, Ravil

**Comment by tengann** [comment]
There are no log files in my 'data' subfolder. When I tried running `docker-compose up` instead, I got the following output with the error: `Failed to validate license, error:  [License validation failed., error: Invalid product key <5>]. Please activate the application using configuration GUI.`
![image](https://user-images.githubusercontent.com/48940092/100399209-cf83ad00-308c-11eb-9ee7-5a6660a560b5.png)
May I know how can the application activation be done?

**Comment by RavilN** [comment]
Activation steps are described at https://onewayautomation.com/visual-logger-docs/html/activate.html#activate
You will need to login first, default credentials are admin/password. If the login dialog window does not appear, click on the Login menu on the top right corner.

**Comment by tengann** [comment]
There are no log files in my `data` subfolder. I only see the following: 
![image](https://user-images.githubusercontent.com/48940092/100399681-acf29380-308e-11eb-9ed1-f7ff3a7b35fd.png)

As mentioned above, I cloned the repository and started the containers but unable to access the web configuration GUI. Therefore, I am unable to activate the license too.

**Comment by RavilN** [comment]
OK, I thought this time the GUI was available, as I can see in terminal messages that the service is started. 
To activate, the GUI is required, but you can not access the GUI. 
Under folder ./data, more files should appear, for example ./data/values.db
Something to do with docker I guess. Folder ./data is not mapped correctly. Maybe for the same reason port 4880 is not mapped to.
 Can you access other URLs, for example Portainer at localhost:9000, grafana at localhost:3000?

**Comment by tengann** [comment]
No, I am not able to access any URLs. I guess I will try to reinstall docker and see how it will go.

**Comment by RavilN** [comment]
Yes, I think that is something to do with Docker.

**Comment by tengann** [comment]
It is still not working after reinstallation of Docker. Therefore, I tried to do [Setup in Windows](https://onewayautomation.com/visual-logger-docs/html/deploy.html#setup-in-windows) as from the website. (Only omitting step 1b, Install / Configure database to store time-series data).

Here are the other two prerequisites installed:
![image](https://user-images.githubusercontent.com/48940092/100407608-ce11af00-30a3-11eb-93cc-1fe38010b073.png)

However, I am still facing the same problem where I cannot access the web configuration GUI. Where can I find log files for this setup to check what may be going wrong?

**Comment by RavilN** [comment]
Log files should be under subfolder data/[InstanceId]/logs of the installation folder, where [InstanceId] is unique identifier. 
If your machine is in a corporate network, then it might be due to your security/firewall settings not allowing opening http ports probably.
If you cannot make it work, please schedule troubleshooting session over web meeting at https://calendly.com/opcfy/ovl

**Comment by RavilN** [comment]
It cannot be reproduced and we did not receive log files to investigate.
