### ISSUE TITLE
Unable to see logged data from Ogamma in Influxdb 2.0

### ISSUE THREAD

**Issue by Jamil100** [onewayautomation/ogamma-logger#18]
I have a established a successful connection between Ogamma and Influxdb however, I am still unable to see my logged data which is found in Ogamma on Influxdb 2.0. I have followed the instructions found [here](https://onewayautomation.com/visual-logger-docs/html/tsdb.html#mapping-opc-ua-to-influxdb). I'm using the Docker image: quay.io/influxdb/influxdb:2.0.0-beta.

**Comment by RavilN** [comment]
Try to enter the application token in the InfluxDB time-series database settings (the Password field).
If that does not help, you can check the Visual Logger application log file (in folder ./data/[InstanceId]/logs/app-log.txt for error messages, as well as look at Influx DB logs.

**Comment by RavilN** [comment]
BTW, InfluxDB has released version 2.0.2 available now, it is better to use the released version than the beta version. 
Upgrade from 2.0 beta to 2.0.1 or 2.0.2 is not automatic, requires some manual steps (https://docs.influxdata.com/influxdb/v2.0/upgrade/v2-beta-to-v2/)

**Comment by Jamil100** [comment]
Thank you for the help. It worked by entering the application token in the Password field.
