### ISSUE TITLE
Adding local OPC UA Server to Ogamma

### ISSUE THREAD

**Issue by Jamil100** [onewayautomation/ogamma-logger#19]
I am facing an issue when adding a new OPC UA Server node in Ogamma. The OPC Server is accessible from the host as it is being run locally in a Docker container on a NAS server. I am adding the ip address of the server in the docker-compose.yml in the extra_hosts section as follows: 
`extra_hosts:
      - '${HOST_NAME:-opcuaserver.com}:${HOST_IP_ADDRESS:-75.152.105.54}'
      - "<hostname>:<ip-address>"
`
While trying to open the OPC UA Server node, I am getting this error: "**Server side error occurred: The server has disconnected from the client.**" (Even though the server is running properly)

**Comment by RavilN** [comment]
Hi,
If both OPC UA Server and ogamma Visual Logger are running in the same docker network, then try to use Docker service name as a host name in the endpoint URL. Also, use original port number of the OPC UA Server (if it was mapped to different port name to access from the Docker host).
If you are running version older than 1.2.5, then upgrading can resolve some connection issues too.
Also, some UA Servers accept only full endpoint URL (with some extra part after port number), you can try to use full endpoint URL too.

**Comment by RavilN** [comment]
In the current version, there are options ``dnsMap`` and ``urlMap`` which can be used to solve connectivity problems like this. Please refer to this section in the User Manual for details: https://onewayautomation.com/visual-logger-docs/html/collect.html?highlight=dnsmap#connecting-to-opc-ua-servers-running-in-docker-container-accessed-over-vpn-or-nat-or-using-port-forwarding
