### ISSUE TITLE
docker-compose up fails due to wrong docker image tag. 

### ISSUE THREAD

**Issue by kBashar** [onewayautomation/ogamma-logger#20]
docker-compose up fails with the error message `ERROR: manifest for ogamma/logger:2.1.14 not found: manifest unknown: manifest unknown`

```
ogamma-logger:
    image: 'ogamma/logger:2.1.14'
    restart: always
```
A search through available tags in [image repository](https://hub.docker.com/r/ogamma/logger/tags) shows, there is no docker image of ogamma/logger tagged '2.1.14'.

Changing line 5 of docker-compose.yml with 'ogamma/logger:latest' solves the issue.

**Comment by RavilN** [comment]
Thank you for reporting this, kBashar!
It is fixed now (changed to the latest version 2.2.2)
It is not set to the ``latest`` tag to eliminate uncontrolled upgrades to newer versions.
